---
name: arrow benchmarks

on:
  push:
    branches: [explore-loop-memory-usage]

jobs:
  run_arrow_benchmarks:
    strategy:
      matrix:
        allocator: ["system","jemalloc","mimalloc"]
        python_version: ["3.9", "3.10"]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}
      ARROW_DEFAULT_MEMORY_POOL: ${{ matrix.allocator }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install poetry
        run: pip install poetry
      - name: Install environment
        run: poetry install --no-interaction --no-ansi
      - name: Profile with memray
        run: | 
          poetry run memray run --output pyarrow_parquet_reads.py.memray.bin \
          --force ./notebooks/examples/pyarrow_parquet_reads.py || true
      - name: Display memray stats from profiling
        run: | 
          poetry run memray stats pyarrow_parquet_reads.py.memray.bin || true
